import { DEFAULT_MENU_THEME } from "../theme/menuTheme";
import type {
  MenuTemplate,
  MenuTemplateCapabilities,
  MenuTemplateId,
} from "../types/menuTemplate.types";

const FOOD_CAPABILITIES: MenuTemplateCapabilities = {
  showHighlights: true,
  showPopular: true,
  showPromotions: true,
  showCombos: true,
  showOptionPreview: true,
  showSearch: true,
  showCategories: true,
  showProductImages: true,
  showDelivery: true,
  showPickup: true,
  cardEmphasis: "balanced",
};

const SERVICE_CAPABILITIES: MenuTemplateCapabilities = {
  showHighlights: false,
  showPopular: false,
  showPromotions: false,
  showCombos: false,
  showOptionPreview: false,
  showSearch: true,
  showCategories: true,
  showProductImages: false,
  showDelivery: false,
  showPickup: true,
  cardEmphasis: "service",
};

/**
 * Commercial template registry.
 * One component tree + config — never `if (niche === ...)`.
 */
export const MENU_TEMPLATE_REGISTRY: Record<MenuTemplateId, MenuTemplate> = {
  generic: {
    id: "generic",
    name: "Geral",
    description: "Modelo neutro para qualquer negócio.",
    niche: "generic",
    defaultCategories: [],
    preview: {
      swatch: ["#2563eb", "#1e40af", "#38bdf8"],
      tagline: "Versátil e limpo",
      pitch: "Modelo neutro para qualquer negócio começar rápido.",
      styleLabel: "Neutro",
      categoryLabel: "Geral",
      tags: ["Neutro", "Versátil", "Catálogo"],
    },
    defaults: {
      theme: {},
      copy: {
        catalogTitle: "Cardápio",
        catalogSubtitle: "Escolha e peça pelo celular",
        highlightsTitle: "Destaques",
        searchPlaceholder: "Buscar no cardápio",
        addToCartLabel: "Adicionar",
        viewCartLabel: "Ver carrinho",
        checkoutLabel: "Finalizar pedido",
        cartTitle: "Carrinho",
        paymentTitle: "Pagamento",
        orderSuccessTitle: "Pedido recebido",
      },
      features: {
        showSearch: true,
        showCategoryTabs: true,
        showHighlights: true,
        showDescriptions: true,
        showProductImages: true,
        showPopularBadge: false,
        showPromotions: true,
        showOptionPreview: false,
        showComboSection: false,
        showDelivery: true,
        showPickup: true,
      },
    },
    capabilities: FOOD_CAPABILITIES,
  },

  acai: {
    id: "acai",
    name: "Açaí",
    description: "Venda rápida com adicionais, combos e promoções.",
    niche: "acai",
    defaultCategories: [
      "Açaí",
      "Sorvetes",
      "Cremes",
      "Adicionais",
      "Bebidas",
      "Combos",
      "Barcas",
    ],
    preview: {
      swatch: ["#7c3aed", "#5b21b6", "#c084fc"],
      tagline: "Monte do seu jeito",
      pitch:
        "Foco em produtos, adicionais e combos.",
      styleLabel: "Vibrante · Comercial",
      categoryLabel: "Alimentação",
      tags: ["Produto", "Combos", "Adicionais"],
    },
    defaults: {
      theme: {
        productLayout: "list",
        density: "comfortable",
        bannerStyle: "image",
        bannerHeight: "sm",
        cardRadius: "xl",
        buttonRadius: "xl",
        imageAspect: "square",
        imageSize: "large",
        cardStyle: "elevated",
        pricePosition: "top",
        ctaPosition: "full",
        catalogColumns: 2,
        buttonStyle: "solid",
        buttonHeight: "lg",
        shadowStyle: "soft",
        headingScale: "lg",
        // Soft seed only — merchant overrides freely.
        primaryColor: "#7c3aed",
        secondaryColor: "#5b21b6",
        accentColor: "#c084fc",
      },
      copy: {
        catalogTitle: "Monte seu açaí",
        catalogSubtitle: "Escolha tamanho, sabores e adicionais",
        highlightsTitle: "Mais pedidos",
        searchPlaceholder: "Buscar açaí, cremes, adicionais",
        customizableLabel: "Monte o seu",
        addToCartLabel: "Adicionar",
        viewCartLabel: "Ver pedido",
        checkoutLabel: "Finalizar pedido",
        cartTitle: "Seu pedido",
        emptyMenuMessage: "Cardápio em atualização. Volte em breve.",
      },
      features: {
        showHighlights: true,
        showPopularBadge: true,
        showPromotions: true,
        showOptionPreview: true,
        showComboSection: true,
        showProductImages: true,
        showDescriptions: true,
        catalogNavigation: "sections",
      },
    },
    capabilities: {
      ...FOOD_CAPABILITIES,
      cardEmphasis: "price",
      showOptionPreview: true,
    },
  },

  cafeteria: {
    id: "cafeteria",
    name: "Cafeteria",
    description: "Visual elegante para bebidas e acompanhamentos.",
    niche: "cafeteria",
    defaultCategories: [
      "Cafés",
      "Bebidas Quentes",
      "Bebidas Geladas",
      "Doces",
      "Salgados",
      "Combos",
    ],
    preview: {
      swatch: ["#92400e", "#78350f", "#d6a36a"],
      tagline: "Escolha sua bebida",
      pitch:
        "Foco em fotografia, tipografia e experiência.",
      styleLabel: "Elegante · Experiência",
      categoryLabel: "Alimentação",
      tags: ["Fotografia", "Tipografia", "Categorias"],
    },
    defaults: {
      theme: {
        productLayout: "list",
        density: "spacious",
        bannerStyle: "minimal",
        bannerHeight: "sm",
        cardRadius: "md",
        buttonRadius: "md",
        imageAspect: "portrait",
        imageSize: "large",
        cardStyle: "flat",
        pricePosition: "bottom",
        ctaPosition: "bottom",
        catalogColumns: 2,
        headingScale: "lg",
        headingFontWeight: "normal",
        shadowStyle: "soft",
        headingFontFamily: "'Geist Variable', Georgia, serif",
        primaryColor: "#92400e",
        secondaryColor: "#78350f",
        accentColor: "#d6a36a",
      },
      copy: {
        catalogTitle: "Escolha sua bebida",
        catalogSubtitle: "Para acompanhar o seu momento",
        highlightsTitle: "Mais pedidos",
        searchPlaceholder: "Buscar cafés, doces, salgados",
        customizableLabel: "Personalizar",
        addToCartLabel: "Adicionar",
        viewCartLabel: "Ver pedido",
      },
      features: {
        showHighlights: true,
        showDescriptions: true,
        showProductImages: true,
        showPopularBadge: true,
        showPromotions: true,
        showComboSection: false,
        catalogNavigation: "sections",
      },
    },
    capabilities: {
      ...FOOD_CAPABILITIES,
      cardEmphasis: "image",
      showCombos: false,
    },
  },

  sushi: {
    id: "sushi",
    name: "Sushi",
    description: "Combos, peças e categorias em destaque.",
    niche: "sushi",
    defaultCategories: [
      "Combos",
      "Hot Rolls",
      "Sashimi",
      "Niguiri",
      "Temakis",
      "Entradas",
      "Bebidas",
    ],
    preview: {
      swatch: ["#b91c1c", "#7f1d1d", "#f87171"],
      tagline: "Escolha suas peças",
      pitch: "Imagem, composição limpa e categorias premium.",
      styleLabel: "Premium · Limpo",
      categoryLabel: "Alimentação",
      tags: ["Imagem", "Premium", "Categorias"],
    },
    defaults: {
      theme: {
        productLayout: "list",
        density: "spacious",
        bannerStyle: "image",
        bannerHeight: "sm",
        bannerOverlay: "soft",
        cardRadius: "lg",
        imageAspect: "landscape",
        imageSize: "large",
        cardStyle: "bordered",
        pricePosition: "inline",
        ctaPosition: "bottom",
        catalogColumns: 2,
        headingScale: "md",
        shadowStyle: "medium",
        primaryColor: "#b91c1c",
        secondaryColor: "#7f1d1d",
        accentColor: "#f87171",
      },
      copy: {
        catalogTitle: "Combos e peças",
        catalogSubtitle: "Escolha suas peças favoritas",
        highlightsTitle: "Mais pedidos",
        searchPlaceholder: "Buscar combos, rolls, temaki",
        customizableLabel: "Escolha as peças",
        addToCartLabel: "Adicionar",
        viewCartLabel: "Ver pedido",
      },
      features: {
        showHighlights: true,
        showComboSection: true,
        showProductImages: true,
        showPopularBadge: true,
        showPromotions: true,
        showOptionPreview: true,
        catalogNavigation: "sections",
      },
    },
    capabilities: {
      ...FOOD_CAPABILITIES,
      cardEmphasis: "image",
      showCombos: true,
    },
  },

  burger: {
    id: "burger",
    name: "Hamburgueria",
    description: "Lanches, combos, adicionais e bebidas.",
    niche: "hamburgueria",
    defaultCategories: [
      "Burgers",
      "Combos",
      "Acompanhamentos",
      "Bebidas",
      "Sobremesas",
    ],
    preview: {
      swatch: ["#ea580c", "#9a3412", "#fb923c"],
      tagline: "Escolha seu lanche",
      pitch: "Combos, preço em destaque e CTA forte.",
      styleLabel: "Impactante · Comercial",
      categoryLabel: "Alimentação",
      tags: ["Combos", "Preço", "CTA"],
    },
    defaults: {
      theme: {
        productLayout: "list",
        density: "compact",
        bannerStyle: "image",
        bannerHeight: "sm",
        cardRadius: "lg",
        imageAspect: "square",
        imageSize: "medium",
        cardStyle: "elevated",
        pricePosition: "top",
        ctaPosition: "full",
        catalogColumns: 2,
        buttonStyle: "solid",
        buttonHeight: "lg",
        shadowStyle: "soft",
        primaryColor: "#ea580c",
        secondaryColor: "#9a3412",
        accentColor: "#fb923c",
      },
      copy: {
        catalogTitle: "Escolha seu lanche",
        catalogSubtitle: "Monte seu combo com adicionais",
        highlightsTitle: "Os favoritos da casa",
        searchPlaceholder: "Buscar burgers, combos, bebidas",
        customizableLabel: "Monte o seu",
        addToCartLabel: "Adicionar",
        viewCartLabel: "Ver pedido",
        checkoutLabel: "Finalizar pedido",
      },
      features: {
        showHighlights: true,
        showComboSection: true,
        showOptionPreview: true,
        showPopularBadge: true,
        showPromotions: true,
        showProductImages: true,
        catalogNavigation: "sections",
      },
    },
    capabilities: {
      ...FOOD_CAPABILITIES,
      cardEmphasis: "price",
    },
  },

  icecream: {
    id: "icecream",
    name: "Sorveteria",
    description: "Tamanhos, sabores e complementos.",
    niche: "sorveteria",
    defaultCategories: [
      "Sorvetes",
      "Milk Shakes",
      "Açaí",
      "Coberturas",
      "Bebidas",
    ],
    preview: {
      swatch: ["#0891b2", "#155e75", "#67e8f9"],
      tagline: "Monte seu sorvete",
      pitch: "Sabores, adicionais e imagem em primeiro plano.",
      styleLabel: "Fresco · Doce",
      categoryLabel: "Alimentação",
      tags: ["Sabores", "Adicionais", "Imagem"],
    },
    defaults: {
      theme: {
        productLayout: "list",
        density: "comfortable",
        bannerStyle: "gradient",
        bannerHeight: "sm",
        cardRadius: "xl",
        imageAspect: "square",
        imageSize: "large",
        cardStyle: "elevated",
        pricePosition: "bottom",
        ctaPosition: "full",
        catalogColumns: 2,
        shadowStyle: "soft",
        primaryColor: "#0891b2",
        secondaryColor: "#155e75",
        accentColor: "#67e8f9",
      },
      copy: {
        catalogTitle: "Monte seu sorvete",
        catalogSubtitle: "Escolha sabores e adicionais",
        highlightsTitle: "Sabores em destaque",
        searchPlaceholder: "Buscar sabores e shakes",
        customizableLabel: "Escolha os sabores",
        addToCartLabel: "Adicionar",
      },
      features: {
        showHighlights: true,
        showOptionPreview: true,
        showPopularBadge: true,
        showPromotions: true,
        showProductImages: true,
        catalogNavigation: "sections",
      },
    },
    capabilities: {
      ...FOOD_CAPABILITIES,
      cardEmphasis: "price",
    },
  },

  pastel: {
    id: "pastel",
    name: "Pastelaria",
    description: "Sabores, tamanhos, adicionais e combos.",
    niche: "pastelaria",
    defaultCategories: ["Pastéis", "Combos", "Sucos", "Refrigerantes", "Doces"],
    preview: {
      swatch: ["#ca8a04", "#a16207", "#fde047"],
      tagline: "Escolha seu pastel",
      pitch: "Visual direto para sabores, tamanhos e combos.",
      styleLabel: "Direto · Rápido",
      categoryLabel: "Alimentação",
      tags: ["Combos", "Preço", "Produto"],
    },
    defaults: {
      theme: {
        productLayout: "list",
        density: "compact",
        bannerStyle: "gradient",
        bannerHeight: "sm",
        cardRadius: "lg",
        cardStyle: "elevated",
        pricePosition: "inline",
        ctaPosition: "inline",
        catalogColumns: 2,
        buttonHeight: "md",
        primaryColor: "#ca8a04",
        secondaryColor: "#a16207",
        accentColor: "#fde047",
      },
      copy: {
        catalogTitle: "Pastéis e combos",
        catalogSubtitle: "Sabores, tamanhos e acompanhamentos",
        highlightsTitle: "Mais pedidos",
        searchPlaceholder: "Buscar pastéis e combos",
        customizableLabel: "Escolha o recheio",
        addToCartLabel: "Adicionar",
      },
      features: {
        showHighlights: true,
        showComboSection: true,
        showProductImages: true,
        showPopularBadge: true,
        catalogNavigation: "sections",
      },
    },
    capabilities: FOOD_CAPABILITIES,
  },

  marmita: {
    id: "marmita",
    name: "Marmitaria",
    description: "Refeições, tamanhos, acompanhamentos e bebidas.",
    niche: "marmitaria",
    defaultCategories: [
      "Marmitas",
      "Pratos",
      "Acompanhamentos",
      "Bebidas",
      "Sobremesas",
    ],
    preview: {
      swatch: ["#16a34a", "#166534", "#86efac"],
      tagline: "Escolha sua refeição",
      pitch: "Visual prático para refeições, tamanhos e bebidas.",
      styleLabel: "Prático · Lista",
      categoryLabel: "Alimentação",
      tags: ["Refeições", "Preço", "Descrição"],
    },
    defaults: {
      theme: {
        productLayout: "list",
        density: "comfortable",
        bannerStyle: "minimal",
        bannerHeight: "sm",
        cardRadius: "md",
        imageAspect: "landscape",
        imageSize: "medium",
        cardStyle: "bordered",
        pricePosition: "inline",
        ctaPosition: "bottom",
        primaryColor: "#16a34a",
        secondaryColor: "#166534",
        accentColor: "#86efac",
      },
      copy: {
        catalogTitle: "Escolha sua refeição",
        catalogSubtitle: "Monte seu prato do dia",
        highlightsTitle: "Pratos do dia",
        searchPlaceholder: "Buscar marmitas e pratos",
        customizableLabel: "Monte seu prato",
        addToCartLabel: "Adicionar",
        viewCartLabel: "Ver pedido",
      },
      features: {
        showHighlights: true,
        showDescriptions: true,
        showProductImages: true,
        showComboSection: false,
        catalogNavigation: "sections",
      },
    },
    capabilities: {
      ...FOOD_CAPABILITIES,
      cardEmphasis: "balanced",
      showCombos: false,
    },
  },

  barbershop: {
    id: "barbershop",
    name: "Barbearia",
    description: "Serviços, preço e duração — não parece cardápio de comida.",
    niche: "barbearia",
    defaultCategories: ["Cortes", "Barba", "Combos", "Tratamentos"],
    preview: {
      swatch: ["#334155", "#0f172a", "#94a3b8"],
      tagline: "Escolha seu serviço",
      pitch: "Serviços, profissionais e CTA Agendar.",
      styleLabel: "Sofisticado · Serviços",
      categoryLabel: "Serviços",
      tags: ["Serviços", "Profissionais", "Agendar"],
    },
    defaults: {
      theme: {
        productLayout: "list",
        density: "spacious",
        bannerStyle: "minimal",
        cardRadius: "md",
        buttonRadius: "md",
        cardStyle: "flat",
        pricePosition: "inline",
        ctaPosition: "full",
        buttonStyle: "solid",
        buttonHeight: "lg",
        headingScale: "md",
        shadowStyle: "none",
        showProductImages: false,
        primaryColor: "#334155",
        secondaryColor: "#0f172a",
        accentColor: "#94a3b8",
      },
      copy: {
        catalogTitle: "Serviços",
        catalogSubtitle: "Escolha o serviço e continue",
        highlightsTitle: "Mais pedidos",
        searchPlaceholder: "Buscar cortes e serviços",
        customizableLabel: "Serviço",
        addToCartLabel: "Agendar",
        viewCartLabel: "Ver seleção",
        checkoutLabel: "Confirmar",
        cartTitle: "Seus serviços",
        paymentTitle: "Pagamento",
        orderSuccessTitle: "Solicitação recebida",
        emptyMenuMessage: "Nenhum serviço disponível no momento.",
        emptySearchMessage: "Nenhum serviço encontrado.",
      },
      features: {
        showHighlights: false,
        showProductImages: false,
        showDescriptions: true,
        showPopularBadge: false,
        showPromotions: false,
        showComboSection: false,
        showOptionPreview: false,
        showDelivery: false,
        showPickup: true,
      },
    },
    capabilities: SERVICE_CAPABILITIES,
  },

  beauty: {
    id: "beauty",
    name: "Beleza",
    description: "Serviços de beleza com preço e duração em destaque.",
    niche: "servicos",
    defaultCategories: [
      "Cabelo",
      "Unhas",
      "Estética",
      "Sobrancelhas",
      "Pacotes",
    ],
    preview: {
      swatch: ["#db2777", "#9d174d", "#f9a8d4"],
      tagline: "Escolha seu cuidado",
      pitch: "Serviços, imagem e estética premium.",
      styleLabel: "Delicado · Premium",
      categoryLabel: "Serviços",
      tags: ["Serviços", "Imagem", "Premium"],
    },
    defaults: {
      theme: {
        productLayout: "list",
        density: "spacious",
        bannerStyle: "minimal",
        bannerHeight: "lg",
        cardRadius: "xl",
        buttonRadius: "xl",
        showProductImages: true,
        imageAspect: "portrait",
        imageSize: "large",
        cardStyle: "elevated",
        pricePosition: "bottom",
        ctaPosition: "full",
        headingScale: "lg",
        shadowStyle: "soft",
        primaryColor: "#db2777",
        secondaryColor: "#9d174d",
        accentColor: "#f9a8d4",
      },
      copy: {
        catalogTitle: "Serviços de beleza",
        catalogSubtitle: "Preço, duração e profissionais",
        highlightsTitle: "Mais pedidos",
        searchPlaceholder: "Buscar serviços",
        customizableLabel: "Serviço",
        addToCartLabel: "Agendar",
        viewCartLabel: "Ver seleção",
        checkoutLabel: "Confirmar",
        cartTitle: "Seus serviços",
        emptyMenuMessage: "Nenhum serviço disponível no momento.",
      },
      features: {
        showHighlights: true,
        showProductImages: true,
        showDescriptions: true,
        showPopularBadge: true,
        showPromotions: true,
        showDelivery: false,
        showPickup: true,
        showComboSection: false,
      },
    },
    capabilities: {
      ...SERVICE_CAPABILITIES,
      showHighlights: true,
      showProductImages: true,
      showPopular: true,
      showPromotions: true,
      cardEmphasis: "service",
    },
  },

  retail: {
    id: "retail",
    name: "Varejo",
    description: "Catálogo com imagem, preço e promoções.",
    niche: "varejo",
    defaultCategories: [],
    preview: {
      swatch: ["#4f46e5", "#312e81", "#a5b4fc"],
      tagline: "Catálogo da loja",
      pitch: "Catálogo organizado com preço e busca.",
      styleLabel: "Catálogo · Organização",
      categoryLabel: "Varejo",
      tags: ["Catálogo", "Preço", "Organização"],
    },
    defaults: {
      theme: {
        productLayout: "grid",
        density: "compact",
        bannerStyle: "image",
        cardRadius: "md",
        imageAspect: "square",
        imageSize: "medium",
        cardStyle: "bordered",
        pricePosition: "top",
        ctaPosition: "inline",
        catalogColumns: 3,
        shadowStyle: "soft",
        primaryColor: "#4f46e5",
        secondaryColor: "#312e81",
        accentColor: "#a5b4fc",
      },
      copy: {
        catalogTitle: "Produtos",
        catalogSubtitle: "Confira preços e promoções",
        highlightsTitle: "Ofertas",
        searchPlaceholder: "Buscar produtos",
        customizableLabel: "Opções",
        addToCartLabel: "Adicionar",
        viewCartLabel: "Ver carrinho",
      },
      features: {
        showHighlights: true,
        showProductImages: true,
        showDescriptions: true,
        showPromotions: true,
        showPopularBadge: false,
        showComboSection: false,
      },
    },
    capabilities: {
      ...FOOD_CAPABILITIES,
      cardEmphasis: "price",
      showCombos: false,
      showOptionPreview: false,
    },
  },

  services: {
    id: "services",
    name: "Serviços",
    description: "Nome, descrição, preço e CTA para serviços gerais.",
    niche: "servicos",
    defaultCategories: ["Serviços", "Pacotes", "Consultorias"],
    preview: {
      swatch: ["#0f766e", "#115e59", "#5eead4"],
      tagline: "Contrate com clareza",
      pitch: "Serviço, descrição e CTA com clareza.",
      styleLabel: "Claro · Serviços",
      categoryLabel: "Serviços",
      tags: ["Serviço", "Descrição", "CTA"],
    },
    defaults: {
      theme: {
        productLayout: "list",
        density: "comfortable",
        bannerStyle: "minimal",
        cardRadius: "md",
        cardStyle: "flat",
        showProductImages: false,
        pricePosition: "inline",
        ctaPosition: "full",
        buttonHeight: "lg",
        headingScale: "md",
        shadowStyle: "none",
        primaryColor: "#0f766e",
        secondaryColor: "#115e59",
        accentColor: "#5eead4",
      },
      copy: {
        catalogTitle: "Nossos serviços",
        catalogSubtitle: "Escolha e continue",
        highlightsTitle: "Mais solicitados",
        searchPlaceholder: "Buscar serviços",
        customizableLabel: "Serviço",
        addToCartLabel: "Solicitar",
        viewCartLabel: "Ver seleção",
        checkoutLabel: "Confirmar",
        cartTitle: "Seleção",
        emptyMenuMessage: "Nenhum serviço disponível no momento.",
      },
      features: {
        showHighlights: false,
        showProductImages: false,
        showDescriptions: true,
        showPromotions: false,
        showDelivery: false,
        showPickup: true,
      },
    },
    capabilities: SERVICE_CAPABILITIES,
  },
};

export const DEFAULT_MENU_TEMPLATE_ID: MenuTemplateId = "generic";

export function isMenuTemplateId(value: unknown): value is MenuTemplateId {
  return typeof value === "string" && value in MENU_TEMPLATE_REGISTRY;
}

export function resolveMenuTemplateId(value: unknown): MenuTemplateId {
  if (isMenuTemplateId(value)) return value;
  return DEFAULT_MENU_TEMPLATE_ID;
}

export function getMenuTemplate(
  id: MenuTemplateId | null | undefined
): MenuTemplate {
  return MENU_TEMPLATE_REGISTRY[resolveMenuTemplateId(id)];
}

export function listMenuTemplates(): MenuTemplate[] {
  return (Object.keys(MENU_TEMPLATE_REGISTRY) as MenuTemplateId[]).map(
    (id) => MENU_TEMPLATE_REGISTRY[id]
  );
}

/** Soft brand seeds used only when applying a template in admin. */
export function templateBrandSeeds(template: MenuTemplate) {
  return {
    primaryColor:
      template.defaults.theme.primaryColor ?? DEFAULT_MENU_THEME.primaryColor,
    secondaryColor:
      template.defaults.theme.secondaryColor ?? DEFAULT_MENU_THEME.secondaryColor,
    accentColor:
      template.defaults.theme.accentColor ?? DEFAULT_MENU_THEME.accentColor,
    backgroundColor:
      template.defaults.theme.backgroundColor ??
      DEFAULT_MENU_THEME.backgroundColor,
  };
}
